# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My Journey in Tech 
description: >- # this means to ignore newlines until "baseurl:"
 This blog is dedicated to sharing my experiences in tech. I'll discuss tools and techniques that I find interesting and useful.  Topics will range from system administration to information security.


 Ping me on Twitter for any comments or feedback.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" #"http://myjourneyintech.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tomwisbrewski
github_username: wisbrewski 
license: CC-BY-SA
author: Tom Wisniewski

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
